import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Pokemon App",
  description: "Generated by David",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body>
        <header className="bg-gray-900 text-white p-4">
          Pokémon Pokédex App
        </header>
        {children}
      </body>
    </html>
  );
}
